steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - build-demo
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python39
